# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Set up JDK
      uses: actions/setup-java@v2 
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64

    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify

    - name: Run unit tests
      run: mvn test clean
      
    - name: Generate reports when coverage requirements are met at compile time
      run: mvn clean test-compile org.pitest:pitest-maven:mutationCoverage -DcoverageThreshold=95 -DmutationThreshold=95

